use crate::diagnostic::{Diagnostic, DiagnosticTier};
use crate::lexer;
use crate::token::RnsToken;

// TODO: generated by opus. looks ok on the first sight, but need to review closely.

/// Helper: tokenize input and return (tokens, diagnostics).
fn tokenize(input: &str) -> (Vec<RnsToken>, Vec<Diagnostic>) {
    lexer::tokenize(input)
}

/// Helper: tokenize and assert exactly one diagnostic was produced. Returns it.
fn expect_one_diagnostic(input: &str) -> Diagnostic {
    let (_, diagnostics) = tokenize(input);
    assert_eq!(
        diagnostics.len(),
        1,
        "expected exactly 1 diagnostic, got {}: {:?}",
        diagnostics.len(),
        diagnostics.iter().map(|d| &d.asm_msg).collect::<Vec<_>>()
    );
    diagnostics.into_iter().next().unwrap()
}

/// Helper: assert diagnostic has the expected message substring and is a SyntaxError.
fn assert_syntax_error(diagnostic: &Diagnostic, expected_message: &str) {
    assert_eq!(
        diagnostic.asm_msg, expected_message,
        "diagnostic message mismatch"
    );
    assert_eq!(diagnostic.tier, DiagnosticTier::SyntaxError);
}

/// Helper: assert diagnostic has the expected error code.
fn assert_error_code(diagnostic: &Diagnostic, expected_code: Option<&str>) {
    assert_eq!(diagnostic.code, expected_code, "error code mismatch");
}

/// Helper: assert the diagnostic's primary location spans the expected byte range.
fn assert_primary_span(diagnostic: &Diagnostic, byte_start: usize, byte_end: usize) {
    assert_eq!(
        diagnostic.primary_location.byte_start, byte_start,
        "byte_start mismatch: expected {}, got {}",
        byte_start, diagnostic.primary_location.byte_start
    );
    assert_eq!(
        diagnostic.primary_location.byte_end, byte_end,
        "byte_end mismatch: expected {}, got {}",
        byte_end, diagnostic.primary_location.byte_end
    );
}

/// Helper: assert the diagnostic's primary location has the expected line/col.
fn assert_primary_lsp(diagnostic: &Diagnostic, line: usize, col_start: usize, col_end: usize) {
    let loc = &diagnostic.primary_location;
    assert_eq!(loc.line, line, "line mismatch");
    assert_eq!(loc.col_start, col_start, "col_start mismatch");
    assert_eq!(loc.col_end, col_end, "col_end mismatch");
}

// =============================================================================
// Unknown Directive errors
// =============================================================================
mod unknown_directive {
    use super::*;

    #[test]
    fn misspelled_directive() {
        let diag = expect_one_diagnostic(".clazz");
        assert_syntax_error(&diag, "unknown directive");
        assert_error_code(&diag, Some("E-002"));
        assert_primary_span(&diag, 0, 6);
        assert_primary_lsp(&diag, 0, 0, 6);
    }

    #[test]
    fn completely_unknown_directive() {
        let diag = expect_one_diagnostic(".foobar");
        assert_syntax_error(&diag, "unknown directive");
        assert_error_code(&diag, Some("E-002"));
        assert_primary_span(&diag, 0, 7);
    }

    #[test]
    fn unknown_directive_with_close_match() {
        // ".metod" is 1 edit away from ".method"
        let diag = expect_one_diagnostic(".metod");
        assert_syntax_error(&diag, "unknown directive");
        assert_error_code(&diag, Some("E-002"));
    }

    #[test]
    fn unknown_directive_on_second_line() {
        let input = ".class\n.foo";
        let (tokens, diagnostics) = tokenize(input);
        assert_eq!(diagnostics.len(), 1);
        assert_syntax_error(&diagnostics[0], "unknown directive");
        assert_error_code(&diagnostics[0], Some("E-002"));
        // .foo starts at byte 7, line 1
        assert_primary_span(&diagnostics[0], 7, 11);
        assert_primary_lsp(&diagnostics[0], 1, 0, 4);
        // .class should still be in tokens
        assert!(tokens.iter().any(|t| matches!(t, RnsToken::DotClass(_))));
    }
}

// =============================================================================
// Unknown TypeHint errors
// =============================================================================
mod unknown_type_hint {
    use super::*;

    #[test]
    fn completely_unknown_type_hint() {
        let diag = expect_one_diagnostic("@foobar");
        assert_syntax_error(&diag, "unknown type hint");
        assert_error_code(&diag, Some("E-005"));
        assert_primary_span(&diag, 0, 7);
        assert_primary_lsp(&diag, 0, 0, 7);
    }

    #[test]
    fn misspelled_type_hint() {
        let diag = expect_one_diagnostic("@unt8");
        assert_syntax_error(&diag, "unknown type hint");
        assert_error_code(&diag, Some("E-005"));
        assert_primary_span(&diag, 0, 5);
    }

    #[test]
    fn case_sensitive_uppercase() {
        // TypeHint matching is case-sensitive: @Utf8 is not @utf8
        let diag = expect_one_diagnostic("@Utf8");
        assert_syntax_error(&diag, "unknown type hint");
        assert_error_code(&diag, Some("E-005"));
    }

    #[test]
    fn case_sensitive_all_caps() {
        let diag = expect_one_diagnostic("@UTF8");
        assert_syntax_error(&diag, "unknown type hint");
        assert_error_code(&diag, Some("E-005"));
    }

    #[test]
    fn case_sensitive_string() {
        let diag = expect_one_diagnostic("@String");
        assert_syntax_error(&diag, "unknown type hint");
        assert_error_code(&diag, Some("E-005"));
    }

    #[test]
    fn unknown_type_hint_on_second_line() {
        let input = "@utf8\n@foobar";
        let (tokens, diagnostics) = tokenize(input);
        assert_eq!(diagnostics.len(), 1);
        assert_syntax_error(&diagnostics[0], "unknown type hint");
        assert_error_code(&diagnostics[0], Some("E-005"));
        // @foobar starts at byte 6, line 1
        assert_primary_span(&diagnostics[0], 6, 13);
        assert_primary_lsp(&diagnostics[0], 1, 0, 7);
        // @utf8 should still be in tokens
        assert!(tokens.iter().any(|t| matches!(t, RnsToken::TypeHint(_))));
    }

    #[test]
    fn multiple_unknown_type_hints() {
        let input = "@foo\n@bar\n@utf8";
        let (tokens, diagnostics) = tokenize(input);
        assert_eq!(diagnostics.len(), 2);
        assert_syntax_error(&diagnostics[0], "unknown type hint");
        assert_syntax_error(&diagnostics[1], "unknown type hint");
        // @utf8 on the third line should still be tokenized
        assert!(tokens.iter().any(|t| matches!(t, RnsToken::TypeHint(_))));
    }

    #[test]
    fn error_skips_rest_of_line() {
        // "@foobar @utf8" on the same line — @utf8 should be skipped
        let input = "@foobar @utf8";
        let (tokens, diagnostics) = tokenize(input);
        assert_eq!(diagnostics.len(), 1);
        assert!(
            !tokens.iter().any(|t| matches!(t, RnsToken::TypeHint(_))),
            "tokens after error on same line should be skipped"
        );
    }

    #[test]
    fn error_recovery_with_valid_next_line() {
        let input = "@foobar\n.class";
        let (tokens, diagnostics) = tokenize(input);
        assert_eq!(diagnostics.len(), 1);
        assert_syntax_error(&diagnostics[0], "unknown type hint");
        assert!(tokens.iter().any(|t| matches!(t, RnsToken::DotClass(_))));
    }
}

// =============================================================================
// Unterminated String errors
// =============================================================================
mod unterminated_string {
    use super::*;

    #[test]
    fn string_missing_closing_quote() {
        let diag = expect_one_diagnostic("\"hello");
        assert_syntax_error(&diag, "unterminated string literal");
        assert_primary_span(&diag, 0, 1);
        assert_primary_lsp(&diag, 0, 0, 1);
    }

    #[test]
    fn string_terminated_by_newline() {
        // The string hits \n before closing quote
        let input = "\"hello\nworld\"";
        let (tokens, diagnostics) = tokenize(input);
        assert_eq!(diagnostics.len(), 1);
        assert_syntax_error(&diagnostics[0], "unterminated string literal");
        // After recovery, "world" on the next line should be tokenized as an identifier
        assert!(
            tokens
                .iter()
                .any(|t| matches!(t, RnsToken::Identifier(s) if s.value == "world\""))
        );
    }

    #[test]
    fn empty_unterminated_string() {
        // Just a single quote mark with nothing after
        let diag = expect_one_diagnostic("\"");
        assert_syntax_error(&diag, "unterminated string literal");
        assert_primary_span(&diag, 0, 1);
    }

    #[test]
    fn string_with_backslash_at_eof() {
        // "\" — backslash consumed, then peek returns None => UnterminatedString
        let diag = expect_one_diagnostic("\"\\");
        assert_syntax_error(&diag, "unterminated string literal");
    }

    #[test]
    fn string_with_backslash_before_newline() {
        // "\<newline>" — backslash followed by literal newline is an invalid escape,
        // not an unterminated string (the user is likely trying line continuation)
        let diag = expect_one_diagnostic("\"\\\n");
        assert_syntax_error(&diag, "invalid escape sequence");
    }

    #[test]
    fn string_with_backslash_before_carriage_return() {
        // "\<CR>" — backslash followed by carriage return is an invalid escape,
        // not an unterminated string (the user is likely trying line continuation)
        let diag = expect_one_diagnostic("\"\\\r");
        assert_syntax_error(&diag, "invalid escape sequence");
    }

    #[test]
    fn unterminated_string_after_valid_token() {
        let input = ".class \"unterminated";
        let diag = expect_one_diagnostic(input);
        assert_syntax_error(&diag, "unterminated string literal");
    }
}

// =============================================================================
// Invalid Escape Sequence errors (NEW — not covered by old tests)
// =============================================================================
mod invalid_escape {
    use super::*;

    #[test]
    fn backslash_q() {
        let diag = expect_one_diagnostic("\"\\q\"");
        assert_syntax_error(&diag, "invalid escape sequence");
    }

    #[test]
    fn backslash_x() {
        let diag = expect_one_diagnostic("\"\\x\"");
        assert_syntax_error(&diag, "invalid escape sequence");
    }

    #[test]
    fn backslash_1() {
        // Numeric escapes (like \1) are not supported
        let diag = expect_one_diagnostic("\"\\1\"");
        assert_syntax_error(&diag, "invalid escape sequence");
    }

    #[test]
    fn backslash_space() {
        let diag = expect_one_diagnostic("\"\\a\"");
        assert_syntax_error(&diag, "invalid escape sequence");
    }

    #[test]
    fn invalid_escape_in_middle_of_string() {
        // "hello\qworld" — error occurs mid-string
        let diag = expect_one_diagnostic("\"hello\\qworld\"");
        assert_syntax_error(&diag, "invalid escape sequence");
    }

    #[test]
    fn valid_escapes_are_not_errors() {
        // Ensure valid escapes don't produce diagnostics
        let (_, diagnostics) = tokenize("\"\\n\\t\\r\\0\\b\\f\\\"\\\\\"");
        assert!(
            diagnostics.is_empty(),
            "valid escapes should not produce errors: {:?}",
            diagnostics.iter().map(|d| &d.asm_msg).collect::<Vec<_>>()
        );
    }
}

// =============================================================================
// Invalid Number errors
// =============================================================================
mod invalid_number {
    use super::*;

    #[test]
    fn integer_overflow() {
        // 2147483648 is i32::MAX + 1
        let diag = expect_one_diagnostic("2147483648");
        assert_syntax_error(&diag, "invalid integer");
        assert_primary_span(&diag, 0, 10);
        assert_primary_lsp(&diag, 0, 0, 10);
    }

    #[test]
    fn negative_overflow() {
        // -2147483649 is i32::MIN - 1
        let diag = expect_one_diagnostic("-2147483649");
        assert_syntax_error(&diag, "invalid integer");
    }

    #[test]
    fn very_large_number() {
        let diag = expect_one_diagnostic("99999999999999");
        assert_syntax_error(&diag, "invalid integer");
    }

    #[test]
    fn hex_prefix() {
        // Hex is not supported yet
        let diag = expect_one_diagnostic("0xFF");
        assert_syntax_error(&diag, "invalid integer");
    }

    #[test]
    fn invalid_chars_in_number() {
        // "123abc" starts with digit so enters read_number, but can't parse
        let diag = expect_one_diagnostic("123abc");
        assert_syntax_error(&diag, "invalid integer");
    }

    #[test]
    fn float_not_supported() {
        // "3.14" starts with digit, read_to_delimiter reads "3.14", parse as i32 fails
        let diag = expect_one_diagnostic("3.14");
        assert_syntax_error(&diag, "invalid integer");
    }

    #[test]
    fn valid_integers_no_errors() {
        for input in ["0", "1", "42", "-1", "2147483647", "-2147483648"] {
            let (_, diagnostics) = tokenize(input);
            assert!(
                diagnostics.is_empty(),
                "input '{}' should not produce errors: {:?}",
                input,
                diagnostics.iter().map(|d| &d.asm_msg).collect::<Vec<_>>()
            );
        }
    }
}

// =============================================================================
// Error Recovery behavior
// =============================================================================
mod error_recovery {
    use super::*;

    #[test]
    fn continues_after_error_on_next_line() {
        // Unknown directive on line 0, valid token on line 1
        let input = ".foobar\n.class";
        let (tokens, diagnostics) = tokenize(input);
        assert_eq!(diagnostics.len(), 1);
        assert_syntax_error(&diagnostics[0], "unknown directive");
        assert!(tokens.iter().any(|t| matches!(t, RnsToken::DotClass(_))));
    }

    #[test]
    fn multiple_errors_on_separate_lines() {
        let input = ".foobar\n.bazqux\n.class";
        let (tokens, diagnostics) = tokenize(input);
        assert_eq!(diagnostics.len(), 2);
        assert!(tokens.iter().any(|t| matches!(t, RnsToken::DotClass(_))));
    }

    #[test]
    fn error_skips_rest_of_line() {
        // ".foobar .class" — error on .foobar should skip to end of line,
        // so .class on the SAME line is NOT tokenized
        let input = ".foobar .class";
        let (tokens, diagnostics) = tokenize(input);
        assert_eq!(diagnostics.len(), 1);
        // .class should NOT appear because it's on the same line as the error
        assert!(
            !tokens.iter().any(|t| matches!(t, RnsToken::DotClass(_))),
            "tokens after error on same line should be skipped"
        );
    }

    #[test]
    fn error_recovery_preserves_newline_tokens() {
        // After skipping to end of line, the \n should still produce a Newline token
        // on the next iteration (since skip_to_end_of_line stops before consuming \n)
        let input = ".foobar\n.class";
        let (tokens, _) = tokenize(input);
        assert!(
            tokens.iter().any(|t| matches!(t, RnsToken::Newline(_))),
            "newline token should be preserved after error recovery"
        );
    }

    #[test]
    fn always_ends_with_eof() {
        // Even with errors, token stream should always end with Eof
        let input = ".foobar .bazqux .xyz";
        let (tokens, _) = tokenize(input);
        assert!(
            matches!(tokens.last(), Some(RnsToken::Eof(_))),
            "token stream should always end with Eof"
        );
    }

    #[test]
    fn no_errors_produces_empty_diagnostics() {
        let (_, diagnostics) = tokenize(".class public MyClass");
        assert!(diagnostics.is_empty());
    }

    #[test]
    fn interleaved_valid_and_invalid_lines() {
        let input = ".class\n.foobar\npublic\n.bazqux\nMyClass";
        let (tokens, diagnostics) = tokenize(input);
        assert_eq!(diagnostics.len(), 2);
        assert!(tokens.iter().any(|t| matches!(t, RnsToken::DotClass(_))));
        assert!(tokens.iter().any(|t| matches!(t, RnsToken::AccessFlag(_))));
        assert!(
            tokens
                .iter()
                .any(|t| matches!(t, RnsToken::Identifier(s) if s.value == "MyClass"))
        );
    }

    #[test]
    fn mixed_error_types_recover() {
        // Line 0: unterminated string, Line 1: unknown directive, Line 2: valid
        let input = "\"unterminated\n.foobar\n.class";
        let (tokens, diagnostics) = tokenize(input);
        assert_eq!(diagnostics.len(), 2);
        assert_syntax_error(&diagnostics[0], "unterminated string literal");
        assert_syntax_error(&diagnostics[1], "unknown directive");
        assert!(tokens.iter().any(|t| matches!(t, RnsToken::DotClass(_))));
    }
}

// =============================================================================
// Help messages — conditional help text based on error context
// =============================================================================
mod help {
    use super::*;

    // -- UnknownDirective --

    #[test]
    fn unknown_directive_with_close_match_suggests() {
        let diag = expect_one_diagnostic(".clazz");
        assert_eq!(diag.help, Some("Did you mean '.class'?".to_string()));
    }

    #[test]
    fn unknown_directive_with_no_close_match() {
        let diag = expect_one_diagnostic(".zzzzzzz");
        assert_eq!(diag.help, None);
    }

    #[test]
    fn unknown_directive_super_typo() {
        let diag = expect_one_diagnostic(".supr");
        assert_eq!(diag.help, Some("Did you mean '.super'?".to_string()));
    }

    // -- UnknownTypeHint --

    #[test]
    fn unknown_type_hint_with_close_match_suggests() {
        let diag = expect_one_diagnostic("@dubble");
        assert_eq!(diag.help, Some("Did you mean '@double'?".to_string()));
    }

    #[test]
    fn unknown_type_hint_with_no_close_match() {
        let diag = expect_one_diagnostic("@zzzzzzz");
        assert_eq!(diag.help, None);
    }

    #[test]
    fn unknown_type_hint_case_sensitive_suggests() {
        // "@Utf8" is 1 edit from "utf8"
        let diag = expect_one_diagnostic("@Utf8");
        assert_eq!(diag.help, Some("Did you mean '@utf8'?".to_string()));
    }

    // -- InvalidInteger --

    #[test]
    fn integer_overflow_help() {
        let diag = expect_one_diagnostic("2147483648");
        assert_eq!(
            diag.help,
            Some(
                "Integers must be between -2147483648 and 2147483647 to fit in a 32-bit signed integer."
                    .to_string()
            )
        );
    }

    #[test]
    fn hex_prefix_help() {
        let diag = expect_one_diagnostic("0xFF");
        assert_eq!(
            diag.help,
            Some(
                "Hexadecimal numbers are not supported yet, but are planned for the future."
                    .to_string()
            )
        );
    }

    #[test]
    fn hex_prefix_uppercase_help() {
        let diag = expect_one_diagnostic("0XFF");
        assert_eq!(
            diag.help,
            Some(
                "Hexadecimal numbers are not supported yet, but are planned for the future."
                    .to_string()
            )
        );
    }

    #[test]
    fn invalid_chars_in_number_help() {
        let diag = expect_one_diagnostic("123abc");
        assert_eq!(
            diag.help,
            Some(
                "Integers can only contain digits and an optional leading minus sign.".to_string()
            )
        );
    }

    #[test]
    fn float_help() {
        let diag = expect_one_diagnostic("3.14");
        assert_eq!(
            diag.help,
            Some(
                "Integers can only contain digits and an optional leading minus sign.".to_string()
            )
        );
    }

    // -- InvalidEscape --

    #[test]
    fn escape_newline_help() {
        let diag = expect_one_diagnostic("\"\\\n");
        assert_eq!(
            diag.help,
            Some(
                "Multiline string literals are not supported yet, but are planned for the future."
                    .to_string()
            )
        );
    }

    #[test]
    fn escape_carriage_return_help() {
        let diag = expect_one_diagnostic("\"\\\r");
        assert_eq!(
            diag.help,
            Some(
                "Multiline string literals are not supported yet, but are planned for the future."
                    .to_string()
            )
        );
    }

    #[test]
    fn escape_regular_char_no_help() {
        let diag = expect_one_diagnostic("\"\\q\"");
        assert_eq!(diag.help, None);
    }

    // -- UnterminatedString --

    #[test]
    fn unterminated_string_help() {
        let diag = expect_one_diagnostic("\"hello");
        assert_eq!(
            diag.help,
            Some("Close the string with a '\"' on the same line.".to_string())
        );
    }
}

// =============================================================================
// Labels — error-specific label text
// =============================================================================
mod labels {
    use super::*;

    fn first_label_msg(diag: &Diagnostic) -> &str {
        &diag.labels[0].message
    }

    // -- UnknownDirective --

    #[test]
    fn unknown_directive_label() {
        let diag = expect_one_diagnostic(".foobar");
        assert_eq!(
            first_label_msg(&diag),
            "'.foobar' is not a recognized directive"
        );
    }

    // -- UnknownTypeHint --

    #[test]
    fn unknown_type_hint_label() {
        let diag = expect_one_diagnostic("@foobar");
        assert_eq!(
            first_label_msg(&diag),
            "'@foobar' is not a recognized type hint"
        );
    }

    // -- UnterminatedString --

    #[test]
    fn unterminated_string_label() {
        let diag = expect_one_diagnostic("\"hello");
        assert_eq!(
            first_label_msg(&diag),
            "this string literal is not terminated"
        );
    }

    // -- InvalidEscape --

    #[test]
    fn invalid_escape_regular_char_label() {
        let diag = expect_one_diagnostic("\"\\q\"");
        assert_eq!(
            first_label_msg(&diag),
            "'\\q' is not a valid escape sequence"
        );
    }

    #[test]
    fn invalid_escape_newline_label() {
        let diag = expect_one_diagnostic("\"\\\n");
        assert_eq!(
            first_label_msg(&diag),
            "newline characters cannot be escaped"
        );
    }

    #[test]
    fn invalid_escape_carriage_return_label() {
        let diag = expect_one_diagnostic("\"\\\r");
        assert_eq!(
            first_label_msg(&diag),
            "carriage return characters cannot be escaped"
        );
    }

    // -- InvalidInteger --

    #[test]
    fn integer_overflow_label() {
        let diag = expect_one_diagnostic("2147483648");
        assert_eq!(
            first_label_msg(&diag),
            "integer '2147483648' is too large for a 32-bit signed integer"
        );
    }

    #[test]
    fn integer_invalid_chars_label() {
        let diag = expect_one_diagnostic("123abc");
        assert_eq!(
            first_label_msg(&diag),
            "'123abc' contains invalid characters"
        );
    }

    #[test]
    fn integer_float_label() {
        let diag = expect_one_diagnostic("3.14");
        assert_eq!(first_label_msg(&diag), "'3.14' contains invalid characters");
    }
}

// =============================================================================
// Note — docs link per error code
// =============================================================================
mod note {
    use super::*;

    #[test]
    fn unterminated_string_note() {
        let diag = expect_one_diagnostic("\"hello");
        assert_eq!(
            diag.note,
            Some("For more details see:\nhttps://rune.lagertha-vm.com/errors/e-001".to_string())
        );
    }

    #[test]
    fn unknown_directive_note() {
        let diag = expect_one_diagnostic(".foobar");
        assert_eq!(
            diag.note,
            Some("For more details see:\nhttps://rune.lagertha-vm.com/errors/e-002".to_string())
        );
    }

    #[test]
    fn invalid_integer_note() {
        let diag = expect_one_diagnostic("2147483648");
        assert_eq!(
            diag.note,
            Some("For more details see:\nhttps://rune.lagertha-vm.com/errors/e-003".to_string())
        );
    }

    #[test]
    fn invalid_escape_note() {
        let diag = expect_one_diagnostic("\"\\q\"");
        assert_eq!(
            diag.note,
            Some("For more details see:\nhttps://rune.lagertha-vm.com/errors/e-004".to_string())
        );
    }

    #[test]
    fn unknown_type_hint_note() {
        let diag = expect_one_diagnostic("@foobar");
        assert_eq!(
            diag.note,
            Some("For more details see:\nhttps://rune.lagertha-vm.com/errors/e-005".to_string())
        );
    }
}

// =============================================================================
// LSP message (lsp_msg) — used by the language server diagnostic output
// =============================================================================
mod lsp_msg {
    use super::*;

    #[test]
    fn unknown_directive_includes_name() {
        // lsp_msg should include the directive name, unlike asm_msg
        let diag = expect_one_diagnostic(".foobar");
        assert_eq!(diag.lsp_msg, "unknown directive '.foobar'");
    }

    #[test]
    fn unknown_directive_differs_from_asm_msg() {
        let diag = expect_one_diagnostic(".clazz");
        assert_eq!(diag.asm_msg, "unknown directive");
        assert_eq!(diag.lsp_msg, "unknown directive '.clazz'");
        assert_ne!(diag.asm_msg, diag.lsp_msg);
    }

    #[test]
    fn unterminated_string_matches_asm_msg() {
        let diag = expect_one_diagnostic("\"hello");
        assert_eq!(diag.lsp_msg, "unterminated string literal");
        assert_eq!(diag.lsp_msg, diag.asm_msg);
    }

    #[test]
    fn invalid_escape_matches_asm_msg() {
        let diag = expect_one_diagnostic("\"\\q\"");
        assert_eq!(diag.lsp_msg, "invalid escape sequence");
        assert_eq!(diag.lsp_msg, diag.asm_msg);
    }

    #[test]
    fn invalid_number_matches_asm_msg() {
        let diag = expect_one_diagnostic("2147483648");
        assert_eq!(diag.lsp_msg, "invalid 32-bit signed integer");
        assert_ne!(diag.lsp_msg, diag.asm_msg);
    }

    #[test]
    fn unknown_type_hint_includes_name() {
        let diag = expect_one_diagnostic("@foobar");
        assert_eq!(diag.lsp_msg, "unknown type hint '@foobar'");
    }

    #[test]
    fn unknown_type_hint_differs_from_asm_msg() {
        let diag = expect_one_diagnostic("@bazqux");
        assert_eq!(diag.asm_msg, "unknown type hint");
        assert_eq!(diag.lsp_msg, "unknown type hint '@bazqux'");
        assert_ne!(diag.asm_msg, diag.lsp_msg);
    }
}
